### ISSUE TITLE
bug: country tracking is broken

### ISSUE THREAD

**Issue by KaelWD** [Swetrix/swetrix#341]
### Dupe Check

- [X] I have [searched Swetrix bugs](https://github.com/swetrix/swetrix/issues?q=is%3Aissue+label%3Abug) and there are no duplicates

### Describe the bug

I've had 38000 unique visitors but only 9 recorded for countries, almost all sessions say "Unknown country".

### To reproduce

1. Self host swetrix
2. Get a bunch of traffic from all over the world

### Screenshots

![Screenshot_20241104_171022](https://github.com/user-attachments/assets/915b0949-5c87-4826-884b-2d526bbf4cf5) ![Screenshot_20241104_171114](https://github.com/user-attachments/assets/a718967d-eb03-4fc6-938f-67aea7b1312b)

### Regression

No, this bug or issue has existed throughout my experience using Swetrix

### Are you using Swetrix cloud version or self-hosted?

I am using Swetrix self-hosted version

### Does this block you from using Swetrix?

No

**Comment by Blaumaus** [comment]
Yep, sorry it's a bug on our side related to incorrect country detection using Cloudflare `cf-ipcountry` header. It will be fixed in the next selfhosted release.

**Comment by Blaumaus** [comment]
This issue is fixed in the linked PR. I'll try to release the next selfhosted version ASAP after I fix other issues. The current version's geolocation tracking will not work properly if you have `CLOUDFLARE_PROXY_ENABLED` set to `true`.

If you need some geo location data, you should set this setting to `false` and the data would be taken from user's timezone that swetrix-js sends with the event. In the next release, the `CLOUDFLARE_PROXY_ENABLED` may be safely put back to `true` if necessary.
